### ISSUE TITLE
How to create deb package

### ISSUE THREAD

**Issue by q4osteam** [seb3773/actioncenter-kicker-applet-legacy#1]
We would like to create deb package from source of this project. Would you recommend a way to do this ? We would like to be able to compile it on our own, so instructions or even better a script would be appreciated.

**Comment by seb3773** [comment]
I will write a little script to compile & create package, will upload it tonight or tomorrow, as soon as I find a bit of time to do it :)

**Comment by seb3773** [comment]
I added "create_deb.sh" script and the "PACKAGE" folder
You can use create_deb.sh with argument "light" or "dark" to create corresponding packages.
for example, in the project folder: 
./create_deb.sh "dark"
will create package : actioncenter_applet_dark.deb   in the project folder.

Due to the fact the buttons bitmaps are localized (well, only en,fr,de and ru for now) , I had to use a postinst script to extract corresponding buttons if an implemented localization is detected (en by default if not)

I am not very satisfied by this, I would like to improve the applet to draw text on buttons instead of using text in bitmaps (this way it will be very easy to implement localizations)
I'm not very good with tqt3, but if someone can help me to improve it, it will be very appreciated :)

**Comment by q4osteam** [comment]
> "I am not very satisfied by this, I would like to improve the applet to draw text on buttons ..."

A way is to create own button class derived from TQPushButton and use TQPainter to paint texts and images on the button. We provide a simple example how to draw customized button label, you will be interested in mybutton.cpp source. Compile the example:
$ tqmake base.pro
$ make

TQT3 assistant application is the perfect TQT classes documentation, install package "tqt3-assistant" to get it.

Find a variety of nice TQT coding examples in /usr/share/doc/tqt3-examples dir, you can easily compile all the examples and see how they work. Install "tqt3-examples" package.

If you need any advice on the provided code or how to code with TQT just ask, we will try to point you on a right direction.
[simpleapp1.tar.gz](https://github.com/user-attachments/files/17351630/simpleapp1.tar.gz)
